# Generated by Django 3.1.5 on 2021-01-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='price',
            new_name='fuel_price',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='routelength',
            new_name='route_length',
        ),
        migrations.AddField(
            model_name='point',
            name='getting_off_friends',
            field=models.ManyToManyField(related_name='_point_getting_off_friends_+', to='app.User', verbose_name='list of friends getting off this point'),
        ),
        migrations.AddField(
            model_name='point',
            name='getting_on_friends',
            field=models.ManyToManyField(related_name='_point_getting_on_friends_+', to='app.User', verbose_name='list of friends getting on this point'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='app.User', verbose_name='list of friends'),
        ),
        migrations.CreateModel(
            name='RouteMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='route_participants',
            field=models.ManyToManyField(through='app.RouteMember', to='app.User'),
        ),
    ]
