# Generated by Django 3.1.5 on 2021-01-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210107_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routemember',
            old_name='price',
            new_name='route_price',
        ),
    ]
