# Generated by Django 3.1.5 on 2021-01-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210107_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RouteParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='routemember',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='routemember',
            name='route',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='combustion',
            new_name='fuel_consumption',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_length',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_participants',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='app.User', verbose_name='list of friends'),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='RouteMember',
        ),
        migrations.AddField(
            model_name='routeparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.user'),
        ),
        migrations.AddField(
            model_name='routeparticipant',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='app.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='participants',
            field=models.ManyToManyField(blank=True, through='app.RouteParticipant', to='app.User'),
        ),
    ]
