# Generated by Django 3.1.5 on 2021-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210107_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='combustion',
            new_name='fuel_consumption',
        ),
        migrations.AlterField(
            model_name='route',
            name='route_participants',
            field=models.ManyToManyField(blank=True, through='app.RouteMember', to='app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='app.User', verbose_name='list of friends'),
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.AddField(
            model_name='landmark',
            name='getting_off_friends',
            field=models.ManyToManyField(blank=True, related_name='_landmark_getting_off_friends_+', to='app.User', verbose_name='list of friends getting off this point'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='getting_on_friends',
            field=models.ManyToManyField(blank=True, related_name='_landmark_getting_on_friends_+', to='app.User', verbose_name='list of friends getting on this point'),
        ),
        migrations.AddField(
            model_name='route',
            name='landmarks',
            field=models.ManyToManyField(blank=True, to='app.Landmark', verbose_name='list of landmarks'),
        ),
    ]
