# Generated by Django 3.1.5 on 2021-01-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210113_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='landmarks',
        ),
        migrations.AddField(
            model_name='landmark',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
    ]
