# Generated by Django 3.1.5 on 2021-01-14 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210112_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.user')),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_length',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='getting_off_friends',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='getting_on_friends',
        ),
        migrations.RemoveField(
            model_name='route',
            name='landmarks',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_participants',
        ),
        migrations.AddField(
            model_name='landmark',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='app.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RouteMember',
        ),
        migrations.AddField(
            model_name='routeparticipant',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='participants',
            field=models.ManyToManyField(blank=True, through='app.RouteParticipant', to='app.User'),
        ),
    ]
