# Generated by Django 3.1.5 on 2021-01-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210113_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='app.route'),
        ),
    ]
