# Generated by Django 3.1.5 on 2021-01-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210114_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_length',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_participants',
        ),
        migrations.DeleteModel(
            name='RouteMember',
        ),
        migrations.AddField(
            model_name='routeparticipant',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='participants',
            field=models.ManyToManyField(blank=True, through='app.RouteParticipant', to='app.User'),
        ),
    ]
