# Generated by Django 3.1.5 on 2021-01-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210114_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.user'),
        ),
    ]
