# Generated by Django 3.1.5 on 2021-01-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210114_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='getting_off_friends',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='getting_on_friends',
        ),
    ]
